# Run with: cmake -DINPUT_DIR=... -DOUTPUT_FILE=... -P embed.cmake
# Reads every file in INPUT_DIR (non-recursive), emits a single C header with
# byte-array literals plus a webapp_routes[] table mapping URL paths to bytes.

if(NOT INPUT_DIR OR NOT OUTPUT_FILE)
    message(FATAL_ERROR "embed.cmake requires -DINPUT_DIR and -DOUTPUT_FILE")
endif()

file(GLOB WEBAPP_FILES RELATIVE "${INPUT_DIR}" "${INPUT_DIR}/*")
list(SORT WEBAPP_FILES)

set(HEADER "// Auto-generated by embed.cmake. DO NOT EDIT.\n#pragma once\n#include <stddef.h>\n\n")
set(ROUTES "")

foreach(F ${WEBAPP_FILES})
    if(IS_DIRECTORY "${INPUT_DIR}/${F}")
        continue()
    endif()

    string(REGEX REPLACE "[^A-Za-z0-9]" "_" VAR "${F}")

    file(READ "${INPUT_DIR}/${F}" HEX HEX)
    string(LENGTH "${HEX}" HEX_LEN)
    math(EXPR BYTE_COUNT "${HEX_LEN} / 2")

    string(REGEX MATCHALL ".." BYTES "${HEX}")
    list(TRANSFORM BYTES PREPEND "0x")
    list(JOIN BYTES "," BYTE_LIST)

    if(F MATCHES "\\.html$")
        set(MIME "text/html; charset=utf-8")
    elseif(F MATCHES "\\.js$")
        set(MIME "application/javascript; charset=utf-8")
    elseif(F MATCHES "\\.css$")
        set(MIME "text/css; charset=utf-8")
    elseif(F MATCHES "\\.svg$")
        set(MIME "image/svg+xml")
    elseif(F MATCHES "\\.webmanifest$")
        set(MIME "application/manifest+json")
    elseif(F MATCHES "\\.json$")
        set(MIME "application/json")
    elseif(F MATCHES "\\.png$")
        set(MIME "image/png")
    else()
        set(MIME "application/octet-stream")
    endif()

    string(APPEND HEADER "static const unsigned char res_${VAR}[] = {${BYTE_LIST}};\n")
    string(APPEND HEADER "static const size_t res_${VAR}_len = ${BYTE_COUNT};\n\n")

    string(APPEND ROUTES "    { \"/${F}\", res_${VAR}, ${BYTE_COUNT}, \"${MIME}\" },\n")
endforeach()

string(APPEND HEADER "typedef struct { const char* path; const unsigned char* data; size_t len; const char* mime; } webapp_route_t;\n\n")
string(APPEND HEADER "static const webapp_route_t webapp_routes[] = {\n${ROUTES}};\n")
string(APPEND HEADER "static const int webapp_routes_count = (int)(sizeof(webapp_routes)/sizeof(webapp_routes[0]));\n")

file(WRITE "${OUTPUT_FILE}" "${HEADER}")
message(STATUS "Embedded ${WEBAPP_FILES} -> ${OUTPUT_FILE}")
